
package GUI.panal;

import GUI.popup.EnrollmentClassSelection;
import GUI.popup.EnrollmentCourseSelection;
import GUI.popup.EnrollmentSelectStudent;
import GUI.popup.UpdateEnrollments;
import java.awt.HeadlessException;
import java.io.IOException;
import javax.swing.JFrame;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.SwingConstants;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import modal.DB;
import modal.HomeInfo;
import modal.LogCenter;
import modal.Reporting;
import modal.beans.Admin;
import modal.beans.Home;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.data.JRTableModelDataSource;
import modal.RoundedPanel;
import java.awt.Color;
import raven.toast.Notifications;

/**
 *
 * @author dell
 */
public class EnrollmentManagement extends javax.swing.JPanel {

    /**
     * Creates new form EnrollmentManagement
     *
     * @param admin
     */
    public EnrollmentManagement(Admin admin) {
        initComponents();
        loadClassesEnrollment();
        loadCoursesEnrollment();
        loadPaymentModel();
        loadStatus();

        classQueryMethod();//class reporting Table load
        courseQueryMethod();// course reporting Table load

        this.admin = admin;
        DefaultTableCellRenderer renderer = new DefaultTableCellRenderer();
        renderer.setHorizontalAlignment(SwingConstants.CENTER);
        enTable.setDefaultRenderer(Object.class, renderer);
        enTable1.setDefaultRenderer(Object.class, renderer);
        enrollmentCourseReportTable.setDefaultRenderer(Object.class, renderer);
        enrollmentClassReportTable.setDefaultRenderer(Object.class, renderer);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPaneEnrollment = new javax.swing.JTabbedPane();
        classEnroll = new RoundedPanel(20, new Color(234,238,244));
        makeEnrollment = new javax.swing.JButton();
        updateEnrollment = new javax.swing.JButton();
        resetEnrollment = new javax.swing.JButton();
        jPanel2 = new RoundedPanel(20, new Color(250,249,246));
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        paymentModelCombobox = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        enrollmentStatusCombobox = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        enTable = new javaswingdev.swing.table.Table();
        jScrollPane2 = new javax.swing.JScrollPane();
        enTable1 = new javaswingdev.swing.table.Table();
        EnrollmentView = new RoundedPanel(20, new Color(234,238,244));
        jPanel1 = new RoundedPanel(20, new Color(250,249,246));
        jPanel8 = new javax.swing.JPanel();
        eClassIdField = new javax.swing.JTextField();
        eClassStudentIdField = new javax.swing.JTextField();
        eClassStudentNicField = new javax.swing.JTextField();
        classEnrolStatusComboBox = new javax.swing.JComboBox<>();
        findClassEnrollmentButton = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        eReportClassClearButton = new javax.swing.JButton();
        eClassViewButton = new javax.swing.JButton();
        eClassPrintButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        enrollmentClassReportTable = new javaswingdev.swing.table.Table();
        jPanel3 = new RoundedPanel(20, new Color(250,249,246));
        jPanel10 = new javax.swing.JPanel();
        eCourseIdField = new javax.swing.JTextField();
        eCourseStudentIdField = new javax.swing.JTextField();
        eCourseStudentNicField = new javax.swing.JTextField();
        courseEnrolStatusCombobox = new javax.swing.JComboBox<>();
        FindCourseEnrollmentButton = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        eCourseReportClearButton = new javax.swing.JButton();
        eCourseViewButton = new javax.swing.JButton();
        eCoursePrintButton = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        enrollmentCourseReportTable = new javaswingdev.swing.table.Table();
        jPanel4 = new RoundedPanel(20, new Color(234,238,244));
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(200, 200, 198));
        setToolTipText("");
        setPreferredSize(new java.awt.Dimension(967, 668));

        jTabbedPaneEnrollment.setBackground(new java.awt.Color(200, 200, 198));
        jTabbedPaneEnrollment.setFont(new java.awt.Font("Poppins SemiBold", 1, 14)); // NOI18N
        jTabbedPaneEnrollment.setPreferredSize(new java.awt.Dimension(967, 698));

        classEnroll.setBackground(new java.awt.Color(200, 200, 198));

        makeEnrollment.setBackground(new java.awt.Color(51, 255, 51));
        makeEnrollment.setFont(new java.awt.Font("Poppins SemiBold", 1, 14)); // NOI18N
        makeEnrollment.setText("Make Enrollment");
        makeEnrollment.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        makeEnrollment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                makeEnrollmentActionPerformed(evt);
            }
        });

        updateEnrollment.setBackground(new java.awt.Color(255, 255, 102));
        updateEnrollment.setFont(new java.awt.Font("Poppins SemiBold", 1, 14)); // NOI18N
        updateEnrollment.setText("Update Enrollment");
        updateEnrollment.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        updateEnrollment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateEnrollmentActionPerformed(evt);
            }
        });

        resetEnrollment.setBackground(new java.awt.Color(255, 51, 51));
        resetEnrollment.setFont(new java.awt.Font("Poppins SemiBold", 1, 14)); // NOI18N
        resetEnrollment.setText("Clear");
        resetEnrollment.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        resetEnrollment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetEnrollmentActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(234, 238, 244));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Student Selection", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        jPanel5.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        jLabel2.setText("Student ID");

        jTextField1.setEditable(false);

        jLabel3.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        jLabel3.setText("First Name");

        jTextField2.setEditable(false);

        jLabel4.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        jLabel4.setText("Last Name");

        jTextField3.setEditable(false);

        jLabel5.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        jLabel5.setText("NIC");

        jTextField4.setEditable(false);
        jTextField4.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
                jTextField4AncestorMoved(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jLabel6.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        jLabel6.setText("Mobile");

        jTextField5.setEditable(false);

        jButton1.setBackground(new java.awt.Color(153, 255, 153));
        jButton1.setFont(new java.awt.Font("Poppins SemiBold", 1, 12)); // NOI18N
        jButton1.setText("Select Student");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                    .addComponent(jTextField1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                    .addComponent(jTextField2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                    .addComponent(jTextField3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                    .addComponent(jTextField4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                        .addGap(149, 149, 149))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jTextField5, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)))
                .addGap(12, 12, 12))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(jLabel5))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jLabel4))
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Class & Course Selection", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        jPanel6.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        jLabel7.setText("Class/Course ID");

        jTextField6.setEditable(false);

        jLabel9.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        jLabel9.setText("Teacher Name");

        jTextField7.setEditable(false);

        jTextField8.setEditable(false);

        jLabel24.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        jLabel24.setText("Type");

        jTextField9.setEditable(false);

        jLabel25.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        jLabel25.setText("Subject");

        jLabel26.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        jLabel26.setText("Grade");

        jTextField10.setEditable(false);

        jButton2.setBackground(new java.awt.Color(255, 255, 153));
        jButton2.setFont(new java.awt.Font("Poppins SemiBold", 1, 14)); // NOI18N
        jButton2.setText("Course");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 204, 204));
        jButton3.setFont(new java.awt.Font("Poppins SemiBold", 1, 14)); // NOI18N
        jButton3.setText("Class");
        jButton3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                    .addComponent(jTextField6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                    .addComponent(jTextField7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                    .addComponent(jTextField8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                    .addComponent(jTextField9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jTextField10, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)))
                .addGap(12, 12, 12))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel26)
                            .addComponent(jLabel25))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel24))
                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel20.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Payment Model");

        paymentModelCombobox.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        paymentModelCombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));

        jLabel21.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Status");

        enrollmentStatusCombobox.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        enrollmentStatusCombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(paymentModelCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(enrollmentStatusCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(8, 8, 8))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(paymentModelCombobox)
                    .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(enrollmentStatusCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5))
        );

        enTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Class Enrollment ID", "Class ID", "Student ID", "Enrollment Status", "Register Date", "Employee", "Payment Model"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        enTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(enTable);

        enTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Class Enrollment ID", "Class ID", "Student ID", "Enrollment Status", "Register Date", "Employee", "Payment Model"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        enTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(enTable1);

        javax.swing.GroupLayout classEnrollLayout = new javax.swing.GroupLayout(classEnroll);
        classEnroll.setLayout(classEnrollLayout);
        classEnrollLayout.setHorizontalGroup(
            classEnrollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(classEnrollLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(classEnrollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, classEnrollLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(resetEnrollment, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(updateEnrollment, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(makeEnrollment, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        classEnrollLayout.setVerticalGroup(
            classEnrollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(classEnrollLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(classEnrollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(makeEnrollment, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateEnrollment, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resetEnrollment, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jTabbedPaneEnrollment.addTab("Enrollment", classEnroll);

        EnrollmentView.setBackground(new java.awt.Color(200, 200, 198));

        jPanel1.setBackground(new java.awt.Color(234, 238, 244));

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Class Enrollment View", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        jPanel8.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N

        eClassIdField.setBackground(new java.awt.Color(240, 240, 240));
        eClassIdField.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        eClassIdField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        eClassStudentIdField.setBackground(new java.awt.Color(240, 240, 240));
        eClassStudentIdField.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        eClassStudentIdField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        eClassStudentNicField.setBackground(new java.awt.Color(240, 240, 240));
        eClassStudentNicField.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        eClassStudentNicField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        classEnrolStatusComboBox.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        classEnrolStatusComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));

        findClassEnrollmentButton.setBackground(new java.awt.Color(102, 255, 153));
        findClassEnrollmentButton.setFont(new java.awt.Font("Poppins SemiBold", 1, 14)); // NOI18N
        findClassEnrollmentButton.setText("Find");
        findClassEnrollmentButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        findClassEnrollmentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findClassEnrollmentButtonActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Search Class ID");

        jLabel13.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Search Student NIC");

        jLabel14.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Search Student ID");

        jLabel18.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Search Status");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(eClassIdField, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                        .addGap(41, 41, 41))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(eClassStudentNicField, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                        .addGap(41, 41, 41))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(eClassStudentIdField, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                        .addGap(42, 42, 42))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(classEnrolStatusComboBox, 0, 152, Short.MAX_VALUE)
                        .addGap(42, 42, 42)
                        .addComponent(findClassEnrollmentButton, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                        .addGap(13, 13, 13))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(eClassStudentIdField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(eClassIdField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(classEnrolStatusComboBox)
                        .addComponent(findClassEnrollmentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(eClassStudentNicField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        eReportClassClearButton.setBackground(new java.awt.Color(255, 51, 51));
        eReportClassClearButton.setFont(new java.awt.Font("Poppins SemiBold", 1, 14)); // NOI18N
        eReportClassClearButton.setText("Clear");
        eReportClassClearButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        eReportClassClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eReportClassClearButtonActionPerformed(evt);
            }
        });

        eClassViewButton.setBackground(new java.awt.Color(0, 102, 204));
        eClassViewButton.setFont(new java.awt.Font("Poppins SemiBold", 1, 14)); // NOI18N
        eClassViewButton.setText("View");
        eClassViewButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        eClassViewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eClassViewButtonActionPerformed(evt);
            }
        });

        eClassPrintButton.setBackground(new java.awt.Color(204, 204, 204));
        eClassPrintButton.setFont(new java.awt.Font("Poppins SemiBold", 1, 14)); // NOI18N
        eClassPrintButton.setText("Export PDF");
        eClassPrintButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        eClassPrintButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eClassPrintButtonActionPerformed(evt);
            }
        });

        enrollmentClassReportTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "EID", "Class ID", "Student ID", "Student NIC", "Student Name", "Teacher ID", "Teacher Name", "Subject ID", "Subject ", "Status", "Register Date", "Employee", "Payment Model", "Class Fee"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        enrollmentClassReportTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(enrollmentClassReportTable);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(eReportClassClearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(eClassViewButton, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(eClassPrintButton, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eReportClassClearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eClassViewButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eClassPrintButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(234, 238, 244));

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Course Enrollment View", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        jPanel10.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N

        eCourseIdField.setBackground(new java.awt.Color(240, 240, 240));
        eCourseIdField.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        eCourseIdField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        eCourseStudentIdField.setBackground(new java.awt.Color(240, 240, 240));
        eCourseStudentIdField.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        eCourseStudentIdField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        eCourseStudentNicField.setBackground(new java.awt.Color(240, 240, 240));
        eCourseStudentNicField.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        eCourseStudentNicField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        courseEnrolStatusCombobox.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        courseEnrolStatusCombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));

        FindCourseEnrollmentButton.setBackground(new java.awt.Color(102, 255, 153));
        FindCourseEnrollmentButton.setFont(new java.awt.Font("Poppins SemiBold", 1, 14)); // NOI18N
        FindCourseEnrollmentButton.setText("Find");
        FindCourseEnrollmentButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        FindCourseEnrollmentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FindCourseEnrollmentButtonActionPerformed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("Search Course ID");

        jLabel27.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("Search Student NIC");

        jLabel28.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("Search Student ID");

        jLabel29.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setText("Search Status");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(eCourseIdField, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                        .addGap(41, 41, 41))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(eCourseStudentNicField, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                        .addGap(41, 41, 41))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel27)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(eCourseStudentIdField, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                        .addGap(42, 42, 42))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel28)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(courseEnrolStatusCombobox, 0, 152, Short.MAX_VALUE)
                        .addGap(42, 42, 42)
                        .addComponent(FindCourseEnrollmentButton, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                        .addGap(13, 13, 13))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel29)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(jLabel27)
                    .addComponent(jLabel28)
                    .addComponent(jLabel29))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(eCourseStudentIdField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(eCourseIdField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(courseEnrolStatusCombobox)
                        .addComponent(FindCourseEnrollmentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(eCourseStudentNicField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        eCourseReportClearButton.setBackground(new java.awt.Color(255, 51, 51));
        eCourseReportClearButton.setFont(new java.awt.Font("Poppins SemiBold", 1, 14)); // NOI18N
        eCourseReportClearButton.setText("Clear");
        eCourseReportClearButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        eCourseReportClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eCourseReportClearButtonActionPerformed(evt);
            }
        });

        eCourseViewButton.setBackground(new java.awt.Color(0, 102, 204));
        eCourseViewButton.setFont(new java.awt.Font("Poppins SemiBold", 1, 14)); // NOI18N
        eCourseViewButton.setText("View");
        eCourseViewButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        eCourseViewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eCourseViewButtonActionPerformed(evt);
            }
        });

        eCoursePrintButton.setBackground(new java.awt.Color(204, 204, 204));
        eCoursePrintButton.setFont(new java.awt.Font("Poppins SemiBold", 1, 14)); // NOI18N
        eCoursePrintButton.setText("Export PDF");
        eCoursePrintButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        eCoursePrintButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eCoursePrintButtonActionPerformed(evt);
            }
        });

        enrollmentCourseReportTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "EID", "Course ID", "Student ID", "Student NIC", "Student Name", "Teacher ID", "Teacher Name", "Subject ID", "Subject ", "Status", "Register Date", "Employee", "Payment Model", "Course Fee"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        enrollmentCourseReportTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane4.setViewportView(enrollmentCourseReportTable);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(eCourseReportClearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(eCourseViewButton, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(eCoursePrintButton, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eCourseReportClearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eCourseViewButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eCoursePrintButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout EnrollmentViewLayout = new javax.swing.GroupLayout(EnrollmentView);
        EnrollmentView.setLayout(EnrollmentViewLayout);
        EnrollmentViewLayout.setHorizontalGroup(
            EnrollmentViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EnrollmentViewLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(EnrollmentViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        EnrollmentViewLayout.setVerticalGroup(
            EnrollmentViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EnrollmentViewLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPaneEnrollment.addTab("View & Report", EnrollmentView);

        jPanel4.setBackground(new java.awt.Color(200, 200, 198));

        jLabel1.setBackground(new java.awt.Color(250, 249, 246));
        jLabel1.setFont(new java.awt.Font("Poppins SemiBold", 1, 20)); // NOI18N
        jLabel1.setText("Enrollment Management");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPaneEnrollment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPaneEnrollment, javax.swing.GroupLayout.DEFAULT_SIZE, 621, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void makeEnrollmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_makeEnrollmentActionPerformed
        setNewEnrollment();
    }//GEN-LAST:event_makeEnrollmentActionPerformed

    private void resetEnrollmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetEnrollmentActionPerformed
        resetData();
    }//GEN-LAST:event_resetEnrollmentActionPerformed

    private void updateEnrollmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateEnrollmentActionPerformed
        JFrame parentFrame = (JFrame) SwingUtilities.getWindowAncestor(this); // Get the JFrame ancestor of the JPanel

        UpdateEnrollments ue = new UpdateEnrollments(parentFrame, true); // Create the dialog, setting parentFrame as its owner
        ue.setVisible(true);

        resetData();

    }//GEN-LAST:event_updateEnrollmentActionPerformed

    private void eReportClassClearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eReportClassClearButtonActionPerformed
        resetclassrepot();
    }//GEN-LAST:event_eReportClassClearButtonActionPerformed

    private void findClassEnrollmentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findClassEnrollmentButtonActionPerformed
        searchclassEnrollmentReport();
    }//GEN-LAST:event_findClassEnrollmentButtonActionPerformed

    private void eClassPrintButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eClassPrintButtonActionPerformed
        try {
            printReportClassEnrollment();
        } catch (Exception e) {
            LogCenter.logger.log(Level.WARNING, "eClassPrintButtonActionPerformed", e);
        }
    }//GEN-LAST:event_eClassPrintButtonActionPerformed

    private void eClassViewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eClassViewButtonActionPerformed
        viweReportClassEnrollment();
    }//GEN-LAST:event_eClassViewButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JFrame parentFrame = (JFrame) SwingUtilities.getWindowAncestor(this); // Get the JFrame ancestor of the JPanel

        EnrollmentSelectStudent uc = new EnrollmentSelectStudent(this, true); // Create the dialog, setting parentFrame as its owner
        uc.setVisible(true);
        uc.setEnrollment(uc);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        JFrame parentFrame = (JFrame) SwingUtilities.getWindowAncestor(this); // Get the JFrame ancestor of the JPanel

        EnrollmentClassSelection uc = new EnrollmentClassSelection(this, true); // Create the dialog, setting parentFrame as its owner
        uc.setVisible(true);
        uc.setEnrollment(uc);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        JFrame parentFrame = (JFrame) SwingUtilities.getWindowAncestor(this); // Get the JFrame ancestor of the JPanel

        EnrollmentCourseSelection uc = new EnrollmentCourseSelection(this, true); // Create the dialog, setting parentFrame as its owner
        uc.setVisible(true);
        uc.setEnrollment(uc);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void FindCourseEnrollmentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FindCourseEnrollmentButtonActionPerformed
        searchCourseEnrollmentReport();
    }//GEN-LAST:event_FindCourseEnrollmentButtonActionPerformed

    private void eCoursePrintButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eCoursePrintButtonActionPerformed
        try {
            printReportCourseEnrollment();
        } catch (Exception e) {
            LogCenter.logger.log(Level.WARNING, "eCoursePrintButtonActionPerformed", e);
        }
    }//GEN-LAST:event_eCoursePrintButtonActionPerformed

    private void eCourseViewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eCourseViewButtonActionPerformed
        viweReportCourseEnrollment();
    }//GEN-LAST:event_eCourseViewButtonActionPerformed

    private void eCourseReportClearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eCourseReportClearButtonActionPerformed
        resetcoursereport();
    }//GEN-LAST:event_eCourseReportClearButtonActionPerformed

    private void jTextField4AncestorMoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jTextField4AncestorMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4AncestorMoved


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel EnrollmentView;
    private javax.swing.JButton FindCourseEnrollmentButton;
    private javax.swing.JComboBox<String> classEnrolStatusComboBox;
    private javax.swing.JPanel classEnroll;
    private javax.swing.JComboBox<String> courseEnrolStatusCombobox;
    private javax.swing.JTextField eClassIdField;
    private javax.swing.JButton eClassPrintButton;
    private javax.swing.JTextField eClassStudentIdField;
    private javax.swing.JTextField eClassStudentNicField;
    private javax.swing.JButton eClassViewButton;
    private javax.swing.JTextField eCourseIdField;
    private javax.swing.JButton eCoursePrintButton;
    private javax.swing.JButton eCourseReportClearButton;
    private javax.swing.JTextField eCourseStudentIdField;
    private javax.swing.JTextField eCourseStudentNicField;
    private javax.swing.JButton eCourseViewButton;
    private javax.swing.JButton eReportClassClearButton;
    private javaswingdev.swing.table.Table enTable;
    private javaswingdev.swing.table.Table enTable1;
    private javaswingdev.swing.table.Table enrollmentClassReportTable;
    private javaswingdev.swing.table.Table enrollmentCourseReportTable;
    private javax.swing.JComboBox<String> enrollmentStatusCombobox;
    private javax.swing.JButton findClassEnrollmentButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPaneEnrollment;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JButton makeEnrollment;
    private javax.swing.JComboBox<String> paymentModelCombobox;
    private javax.swing.JButton resetEnrollment;
    private javax.swing.JButton updateEnrollment;
    // End of variables declaration//GEN-END:variables

    private Admin admin;
    private EnrollmentSelectStudent uc;
    private EnrollmentClassSelection eCS;
    private EnrollmentCourseSelection eCoS;

    private static HashMap<String, String> paymentModelMap = new HashMap<>(); //for get id from payment model
    private static HashMap<String, String> enrollmentStatusMap = new HashMap<>(); //for get id from status

    public JTextField getjTextField1() {
        return jTextField1;
    }

    public JTextField getjTextField2() {
        return jTextField2;
    }

    public JTextField getjTextField3() {
        return jTextField3;
    }

    public JTextField getjTextField4() {
        return jTextField4;
    }

    public JTextField getjTextField5() {
        return jTextField5;
    }

    public JTextField getjTextField6() {
        return jTextField6;
    }

    public JTextField getjTextField7() {
        return jTextField7;
    }

    public JTextField getjTextField8() {
        return jTextField8;
    }

    public JTextField getjTextField9() {
        return jTextField9;
    }

    public JTextField getjTextField10() {
        return jTextField10;
    }

    private void loadClassesEnrollment() {

        try {

            ResultSet resultSet = DB.search("SELECT * FROM `class_enrollment`"
                    + "INNER JOIN `class` ON `class`.`id` = `class_enrollment`.`class_id`"
                    + "INNER JOIN `student` ON `student`.`id` = `class_enrollment`.`student_id`"
                    + "INNER JOIN `enrollment_status` ON `enrollment_status`.`id` = `class_enrollment`.`enrollment_status_id`"
                    + "INNER JOIN `employee` ON `employee`.`id` = `class_enrollment`.`employee_id`"
                    + "INNER JOIN `payment_modal` ON `payment_modal`.`id` = `class_enrollment`.`payment_modal_id` "
                    + "ORDER BY `class_enrollment`.`id` ASC");

            DefaultTableModel tableModel = (DefaultTableModel) enTable.getModel();
            tableModel.setRowCount(0);

            while (resultSet.next()) {
                Vector vector = new Vector();
                vector.add(resultSet.getString("id"));
                vector.add(resultSet.getString("class.id"));
                vector.add(resultSet.getString("student.id"));
                vector.add(resultSet.getString("enrollment_status.name"));
                vector.add(resultSet.getString("register_date"));
                vector.add(resultSet.getString("employee.fname") + " " + resultSet.getString("employee.lname"));
                vector.add(resultSet.getString("payment_modal.modal"));

                tableModel.addRow(vector);
            }

        } catch (ClassNotFoundException | SQLException e) {
            LogCenter.logger.log(Level.WARNING, "loadClassesEnrollment", e);
        } catch (IOException ex) {
            LogCenter.logger.log(java.util.logging.Level.WARNING, "Database Connecting Problem", ex);
        }

    }

    private void loadPaymentModel() {

        try {

            ResultSet resultSet = DB.search("SELECT * FROM `payment_modal`");

            Vector<String> vector = new Vector<>();

            vector.add("Select");

            while (resultSet.next()) {
                vector.add(resultSet.getString("modal"));
                paymentModelMap.put(resultSet.getString("modal"), resultSet.getString("id"));

            }

            DefaultComboBoxModel<String> comboBoxModel = new DefaultComboBoxModel<>(vector);
            paymentModelCombobox.setModel(comboBoxModel);

        } catch (ClassNotFoundException | SQLException e) {
            LogCenter.logger.log(Level.WARNING, "loadPaymentModel", e);
        } catch (IOException ex) {
            LogCenter.logger.log(java.util.logging.Level.WARNING, "Database Connecting Problem", ex);
        }

    }

    private void loadStatus() {
        try {

            ResultSet resultSet = DB.search("SELECT * FROM `enrollment_status`");

            Vector<String> vector = new Vector<>();

            vector.add("Select");

            while (resultSet.next()) {
                vector.add(resultSet.getString("name"));
                enrollmentStatusMap.put(resultSet.getString("name"), resultSet.getString("id"));

            }

            DefaultComboBoxModel<String> comboBoxModel = new DefaultComboBoxModel<>(vector);

            DefaultComboBoxModel<String> comboBoxModelclassReport = new DefaultComboBoxModel<>(vector);// class report
            DefaultComboBoxModel<String> comboBoxModelcourseReport = new DefaultComboBoxModel<>(vector);//course report

            enrollmentStatusCombobox.setModel(comboBoxModel);

            classEnrolStatusComboBox.setModel(comboBoxModelclassReport);// class report
            courseEnrolStatusCombobox.setModel(comboBoxModelcourseReport);//course report

        } catch (ClassNotFoundException | SQLException e) {
            LogCenter.logger.log(Level.WARNING, "loadStatus", e);
        } catch (IOException ex) {
            LogCenter.logger.log(java.util.logging.Level.WARNING, "Database Connecting Problem", ex);
        }

    }

    private void loadCoursesEnrollment() {
        try {

            ResultSet resultSet = DB.search("SELECT * FROM `course_enrollment`"
                    + "INNER JOIN `course` ON `course`.`id` = `course_enrollment`.`course_id`"
                    + "INNER JOIN `student` ON `student`.`id` = `course_enrollment`.`student_id`"
                    + "INNER JOIN `enrollment_status` ON `enrollment_status`.`id` = `course_enrollment`.`enrollment_status_id`"
                    + "INNER JOIN `employee` ON `employee`.`id` = `course_enrollment`.`employee_id`"
                    + "INNER JOIN `payment_modal` ON `payment_modal`.`id` = `course_enrollment`.`payment_modal_id` "
                    + "ORDER BY `course_enrollment`.`id` ASC");

            DefaultTableModel tableModel = (DefaultTableModel) enTable1.getModel();
            tableModel.setRowCount(0);

            while (resultSet.next()) {
                Vector vector = new Vector();
                vector.add(resultSet.getString("id"));
                vector.add(resultSet.getString("course.id"));
                vector.add(resultSet.getString("student.id"));
                vector.add(resultSet.getString("enrollment_status.name"));
                vector.add(resultSet.getString("register_date"));
                vector.add(resultSet.getString("employee.fname") + " " + resultSet.getString("employee.lname"));
                vector.add(resultSet.getString("payment_modal.modal"));

                tableModel.addRow(vector);
            }

        } catch (ClassNotFoundException | SQLException e) {
            LogCenter.logger.log(Level.WARNING, "loadCoursesEnrollment", e);
        } catch (IOException ex) {
            LogCenter.logger.log(java.util.logging.Level.WARNING, "Database Connecting Problem", ex);
        }

    }

    private void setNewEnrollment() {
        try {

            String sID = jTextField5.getText();
            String cID = jTextField6.getText();
            String pModel = String.valueOf(paymentModelCombobox.getSelectedItem());
            String eStatus = String.valueOf(enrollmentStatusCombobox.getSelectedItem());

            String curruntDate = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(new Date());

            if (sID.isEmpty()) {
                Notifications.getInstance().show(Notifications.Type.WARNING, Notifications.Location.TOP_CENTER,
                    "Select A Student");
            } else if (cID.isEmpty()) {
                Notifications.getInstance().show(Notifications.Type.WARNING, Notifications.Location.TOP_CENTER,
                    "Select A Class");
            } else if (pModel.equals("Select")) {
                Notifications.getInstance().show(Notifications.Type.WARNING, Notifications.Location.TOP_CENTER,
                    "Select A Payment Model");
            } else if (eStatus.equals("Select")) {
                Notifications.getInstance().show(Notifications.Type.WARNING, Notifications.Location.TOP_CENTER,
                    "Select Status");
            } else {
                //insert class enrollment
                if (cID.matches("CL\\d{6}")) {
                    ResultSet resultset = DB.search("SELECT * FROM `class_enrollment` WHERE `class_id` = '" + cID + "' AND `student_id` = '" + sID + "'");

                    if (resultset.next()) {
                        Notifications.getInstance().show(Notifications.Type.WARNING, Notifications.Location.TOP_CENTER,
                    "Already Exists");
                    } else {
                        DB.IUD("INSERT INTO `class_enrollment` (`class_id`, `student_id`, `enrollment_status_id`, `register_date`, `employee_id`, `payment_modal_id`)"
                                + "VALUES ('" + cID + "', '" + sID + "', '" + enrollmentStatusMap.get(eStatus) + "', '" + curruntDate + "', '" + admin.getUserID() + "', '" + paymentModelMap.get(pModel) + "') ");

                        Notifications.getInstance().show(Notifications.Type.SUCCESS, Notifications.Location.TOP_CENTER,
                    "Insert Class Enrollment is Successfull");
                        resetData();
                    }

                    //inert course enrollment
                } else if (cID.matches("CO\\d{6}")) {

                    ResultSet resultset = DB.search("SELECT * FROM `course_enrollment` WHERE `course_id` = '" + cID + "' AND `student_id` = '" + sID + "'");

                    if (resultset.next()) {
                        Notifications.getInstance().show(Notifications.Type.WARNING, Notifications.Location.TOP_CENTER,
                    "Already Exists");
                    } else {
                        DB.IUD("INSERT INTO `course_enrollment` (`student_id`, `course_id`, `enrollment_status_id`, `register_date`, `employee_id`, `payment_modal_id`)"
                                + "VALUES ('" + sID + "', '" + cID + "', '" + enrollmentStatusMap.get(eStatus) + "', '" + curruntDate + "', '" + admin.getUserID() + "', '" + paymentModelMap.get(pModel) + "') ");

                        Notifications.getInstance().show(Notifications.Type.SUCCESS, Notifications.Location.TOP_CENTER,
                    "Insert Course Enrollment is Successfull");
                        resetData();

                    }

                }

            }

        } catch (HeadlessException | ClassNotFoundException | SQLException e) {
            LogCenter.logger.log(Level.WARNING, "setNewEnrollment", e);
        } catch (IOException ex) {
            LogCenter.logger.log(java.util.logging.Level.WARNING, "Database Connecting Problem", ex);
        }
    }

    private void resetData() {
        jTextField5.setText("");
        jTextField6.setText("");
        jTextField7.setText("");
        jTextField8.setText("");
        jTextField9.setText("");
        jTextField6.setText("");
        jTextField7.setText("");
        jTextField8.setText("");
        jTextField9.setText("");
        jTextField10.setText("");
        paymentModelCombobox.setSelectedIndex(0);
        enrollmentStatusCombobox.setSelectedIndex(0);
        loadClassesEnrollment();
        loadCoursesEnrollment();
    }

    //reporting-------------
    // class enrollment reporting------------------------------------------------------------------------------------------------------------------
    private String generateClassScheduleQuery(String condition) {
        return "SELECT * FROM `class_enrollment`"
                + "INNER JOIN `class` ON `class`.`id` = `class_enrollment`.`class_id`"
                + "INNER JOIN `teacher` ON `teacher`.`nic` = `class`.`teacher_nic` "
                + "INNER JOIN `student` ON `student`.`id` = `class_enrollment`.`student_id`"
                + "INNER JOIN `subject` ON `subject`.`id` = `class`.`subject_id`"
                + "INNER JOIN `enrollment_status` ON `enrollment_status`.`id` = `class_enrollment`.`enrollment_status_id`"
                + "INNER JOIN `employee` ON `employee`.`id` = `class_enrollment`.`employee_id`"
                + "INNER JOIN `payment_modal` ON `payment_modal`.`id` = `class_enrollment`.`payment_modal_id`"
                + "WHERE "
                + condition
                + " ORDER BY `class_enrollment`.`id` ASC";
    }

    private void loadViewClassData(String query) {
        try {

            ResultSet resultSet = DB.search(query);

            DefaultTableModel tableModel = (DefaultTableModel) enrollmentClassReportTable.getModel();
            tableModel.setRowCount(0);

            while (resultSet.next()) {
                Vector vector = new Vector();
                vector.add(resultSet.getString("id"));
                vector.add(resultSet.getString("class.id"));
                vector.add(resultSet.getString("student.id"));
                vector.add(resultSet.getString("student.nic"));
                vector.add(resultSet.getString("student.fname") + " " + resultSet.getString("student.lname"));
                vector.add(resultSet.getString("teacher.nic"));
                vector.add(resultSet.getString("teacher.lname") + " " + resultSet.getString("teacher.lname"));
                vector.add(resultSet.getString("subject.id"));
                vector.add(resultSet.getString("subject.name"));
                vector.add(resultSet.getString("enrollment_status.name"));
                vector.add(resultSet.getString("register_date"));
                vector.add(resultSet.getString("employee.fname") + " " + resultSet.getString("employee.lname"));
                vector.add(resultSet.getString("payment_modal.modal"));
                vector.add(resultSet.getString("class.fee"));

                tableModel.addRow(vector);
            }

        } catch (ClassNotFoundException | SQLException e) {
            LogCenter.logger.log(Level.WARNING, "loadViewClassData", e);
        } catch (IOException ex) {
            LogCenter.logger.log(java.util.logging.Level.WARNING, "Database Connecting Problem", ex);
        }
    }

    private void classQueryMethod() {

        loadViewClassData("SELECT * FROM `class_enrollment`"
                + "INNER JOIN `class` ON `class`.`id` = `class_enrollment`.`class_id`"
                + "INNER JOIN `teacher` ON `teacher`.`nic` = `class`.`teacher_nic` "
                + "INNER JOIN `student` ON `student`.`id` = `class_enrollment`.`student_id`"
                + "INNER JOIN `subject` ON `subject`.`id` = `class`.`subject_id`"
                + "INNER JOIN `enrollment_status` ON `enrollment_status`.`id` = `class_enrollment`.`enrollment_status_id`"
                + "INNER JOIN `employee` ON `employee`.`id` = `class_enrollment`.`employee_id`"
                + "INNER JOIN `payment_modal` ON `payment_modal`.`id` = `class_enrollment`.`payment_modal_id` "
                + "ORDER BY `class_enrollment`.`id` ASC");

    }

    private void searchclassEnrollmentReport() {
        // Capture search inputs from the UI (ensure these fields are initialized in your form)
        String classID = eClassIdField.getText().trim();
        String studentNIC = eClassStudentNicField.getText().trim();
        String studentID = eClassStudentIdField.getText().trim();
        String status = classEnrolStatusComboBox.getSelectedItem().toString().trim();

        // Build condition dynamically
        StringBuilder condition = new StringBuilder("1=1"); // Default condition to allow all results

        // Add conditions based on input fields, ensuring no extra AND if condition is empty
        if (!classID.isEmpty()) {
            condition.append(" AND `class`.`id` LIKE '%").append(classID).append("%'");
        }
        if (!studentNIC.isEmpty()) {
            condition.append(" AND `student`.`nic` LIKE '%").append(studentNIC).append("%'");
        }
        if (!studentID.isEmpty()) {
            condition.append(" AND `student`.`id` LIKE '%").append(studentID).append("%'");
        }
        if (!status.equals("Select")) {
            condition.append(" AND `enrollment_status`.`name` = '").append(status).append("'");
        }

        // Generate query with dynamic conditions
        String query = generateClassScheduleQuery(condition.toString());

        // Load data into the table using the generated query
        loadViewClassData(query);

    }

    private void resetclassrepot() {
        eClassIdField.setText("");
        eClassStudentIdField.setText("");
        eClassStudentNicField.setText("");
        classEnrolStatusComboBox.setSelectedIndex(0);
        classQueryMethod();
    }
    // class enrollment reporting-----------------------------------------------------------------------------------------------------------

    // course Enrollment Reporting----------------------------------------------------------------------------------------------------------
    private String generateCourseScheduleQuery(String condition) {
        return "SELECT * FROM `course_enrollment`"
                + "INNER JOIN `course` ON `course`.`id` = `course_enrollment`.`course_id`"
                + "INNER JOIN `teacher` ON `teacher`.`nic` = `course`.`teacher_nic` "
                + "INNER JOIN `student` ON `student`.`id` = `course_enrollment`.`student_id`"
                + "INNER JOIN `subject` ON `subject`.`id` = `course`.`subject_id`"
                + "INNER JOIN `enrollment_status` ON `enrollment_status`.`id` = `course_enrollment`.`enrollment_status_id`"
                + "INNER JOIN `employee` ON `employee`.`id` = `course_enrollment`.`employee_id`"
                + "INNER JOIN `payment_modal` ON `payment_modal`.`id` = `course_enrollment`.`payment_modal_id` "
                + "WHERE "
                + condition
                + " ORDER BY `course_enrollment`.`id` ASC";
    }

    private void loadViewCoursData(String query) {
        try {

            ResultSet resultSet = DB.search(query);

            DefaultTableModel tableModel = (DefaultTableModel) enrollmentCourseReportTable.getModel();
            tableModel.setRowCount(0);

            while (resultSet.next()) {
                Vector vector = new Vector();
                vector.add(resultSet.getString("id"));
                vector.add(resultSet.getString("course.id"));
                vector.add(resultSet.getString("student.id"));
                vector.add(resultSet.getString("student.nic"));
                vector.add(resultSet.getString("student.fname") + " " + resultSet.getString("student.lname"));
                vector.add(resultSet.getString("teacher.nic"));
                vector.add(resultSet.getString("teacher.lname") + " " + resultSet.getString("teacher.lname"));
                vector.add(resultSet.getString("subject.id"));
                vector.add(resultSet.getString("subject.name"));
                vector.add(resultSet.getString("enrollment_status.name"));
                vector.add(resultSet.getString("register_date"));
                vector.add(resultSet.getString("employee.fname") + " " + resultSet.getString("employee.lname"));
                vector.add(resultSet.getString("payment_modal.modal"));
                vector.add(resultSet.getString("course.fee"));
                tableModel.addRow(vector);
            }

        } catch (ClassNotFoundException | SQLException e) {
            LogCenter.logger.log(Level.WARNING, "loadViewCoursData", e);
        } catch (IOException ex) {
            LogCenter.logger.log(java.util.logging.Level.WARNING, "Database Connecting Problem", ex);
        }
    }

    private void courseQueryMethod() {

        loadViewCoursData("SELECT * FROM `course_enrollment`"
                + "INNER JOIN `course` ON `course`.`id` = `course_enrollment`.`course_id`"
                + "INNER JOIN `teacher` ON `teacher`.`nic` = `course`.`teacher_nic` "
                + "INNER JOIN `student` ON `student`.`id` = `course_enrollment`.`student_id`"
                + "INNER JOIN `subject` ON `subject`.`id` = `course`.`subject_id`"
                + "INNER JOIN `enrollment_status` ON `enrollment_status`.`id` = `course_enrollment`.`enrollment_status_id`"
                + "INNER JOIN `employee` ON `employee`.`id` = `course_enrollment`.`employee_id`"
                + "INNER JOIN `payment_modal` ON `payment_modal`.`id` = `course_enrollment`.`payment_modal_id` "
                + "ORDER BY `course_enrollment`.`id` ASC");

    }

    private void searchCourseEnrollmentReport() {
        // Capture search inputs
        String courseID = eCourseIdField.getText().trim();
        String studentNIC = eCourseStudentNicField.getText().trim();
        String studentID = eCourseStudentIdField.getText().trim();
        String status = courseEnrolStatusCombobox.getSelectedItem().toString().trim();

        // Build condition dynamically
        StringBuilder condition = new StringBuilder("1=1"); // Default condition to allow all results

        // Add conditions based on input fields, ensuring no extra AND if condition is empty
        if (!courseID.isEmpty()) {
            condition.append(" AND `course`.`id` LIKE '%").append(courseID).append("%'");
        }
        if (!studentNIC.isEmpty()) {
            condition.append(" AND `student`.`nic` LIKE '%").append(studentNIC).append("%'");
        }
        if (!studentID.isEmpty()) {
            condition.append(" AND `student`.`id` LIKE '%").append(studentID).append("%'");
        }
        if (!status.equals("Select")) {
            condition.append(" AND `enrollment_status`.`name` = '").append(status).append("'");
        }

        // Generate query with dynamic conditions
        String query = generateCourseScheduleQuery(condition.toString());

        // Load data into the table using the generated query
        loadViewCoursData(query);

    }

    private void resetcoursereport() {
        eCourseIdField.setText("");
        eCourseStudentIdField.setText("");
        eCourseStudentNicField.setText("");
        courseEnrolStatusCombobox.setSelectedIndex(0);
        courseQueryMethod();
    }
    // course Enrollment Reporting----------------------------------------------------------------------------------------------------------

    //class Enrollment reporting print------------------------------------------------------------------------------------------------------
    private void printReportClassEnrollment() throws JRException {

        try {
            // Use JRTableModelDataSource from jTable1's model
            JRTableModelDataSource dataSource = new JRTableModelDataSource(enrollmentClassReportTable.getModel());

            // Get system data
            Home home = new HomeInfo().getHome();

            // Parameters for the report
            HashMap<String, Object> params = new HashMap<>();
            params.put("address", home.getLine01() + "," + home.getLine02() + "," + home.getCity());
            params.put("landLine", home.getLandLine());
            params.put("email", home.getEmail());
            params.put("mobile", home.getMobile());
            params.put("title", "Student Class Enrollment Report");

            // Create an Admin instance (assuming you have access to it in this context)
            // Use saveReport method to save the report
            Reporting reporting = new Reporting();
            boolean isSaved = reporting.saveReport("Student_Class_Enrollment_Report", params, dataSource, admin);

            if (isSaved) {
                Notifications.getInstance().show(Notifications.Type.SUCCESS, Notifications.Location.TOP_CENTER,
                    "Student Class Enrollment Report saved successfully");
            } else {
                Notifications.getInstance().show(Notifications.Type.ERROR, Notifications.Location.TOP_CENTER,
                    "Student Class Enrollment Report saving was canceled");
            }

        } catch (IOException ex) {
            LogCenter.logger.log(Level.WARNING, "I/O error occurred while printing the report", ex);
        } catch (JRException ex) {
            LogCenter.logger.log(Level.WARNING, "Error occurred while generating the report", ex);
        } catch (Exception ex) {
            // Catch any other unexpected exceptions
            LogCenter.logger.log(Level.WARNING, "Unexpected error occurred while printing the report", ex);
        }
    }
    //class Enrollment reporting print------------------------------------------------------------------------------------------------------

    //class Enrollment reporting view-------------------------------------------------------------------------------------------------------
    private void viweReportClassEnrollment() {
        Home home;
        try {
            home = new HomeInfo().getHome();
            JRTableModelDataSource dataSource = new JRTableModelDataSource(enrollmentClassReportTable.getModel());
            HashMap<String, Object> params = new HashMap<>();
            params.put("landLine", home.getLandLine());
            params.put("email", home.getEmail());
            params.put("mobile", home.getMobile());
            params.put("address", home.getLine01() + " " + home.getLine02() + " " + home.getCity());
            params.put("title", "Student Class Enrollment Report");

            new Reporting().viewReport("Student_Class_Enrollment_Report", params, dataSource, admin);

        } catch (IOException ex) {
            LogCenter.logger.log(Level.WARNING, "Error", ex);
        } catch (ClassNotFoundException ex) {
            LogCenter.logger.log(Level.WARNING, "Error", ex);
        } catch (JRException ex) {
            Logger.getLogger(PaymentManagement.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    //class Enrollment reporting view-------------------------------------------------------------------------------------------------------
    //course Enrollment reporting print-----------------------------------------------------------------------------------------------------
    private void printReportCourseEnrollment() throws JRException {

        try {
            // Use JRTableModelDataSource from jTable1's model
            JRTableModelDataSource dataSource = new JRTableModelDataSource(enrollmentCourseReportTable.getModel());

            // Get system data
            Home home = new HomeInfo().getHome();

            // Parameters for the report
            HashMap<String, Object> params = new HashMap<>();
            params.put("address", home.getLine01() + "," + home.getLine02() + "," + home.getCity());
            params.put("landLine", home.getLandLine());
            params.put("email", home.getEmail());
            params.put("mobile", home.getMobile());
            params.put("title", "Student Course Enrollment Report");

            // Create an Admin instance (assuming you have access to it in this context)
            // Use saveReport method to save the report
            Reporting reporting = new Reporting();
            boolean isSaved = reporting.saveReport("Student_Course_Enrollment_Report", params, dataSource, admin);

            if (isSaved) {
                JOptionPane.showMessageDialog(this, "Student Course Enrollment Report saved successfully");
            } else {
                JOptionPane.showMessageDialog(this, "Student Course Enrollment Report saving was canceled");
            }

        } catch (IOException ex) {
            LogCenter.logger.log(Level.WARNING, "I/O error occurred while printing the report", ex);
        } catch (JRException ex) {
            LogCenter.logger.log(Level.WARNING, "Error occurred while generating the report", ex);
        } catch (Exception ex) {
            // Catch any other unexpected exceptions
            LogCenter.logger.log(Level.WARNING, "Unexpected error occurred while printing the report", ex);
        }
    }

    //course Enrollment reporting print-----------------------------------------------------------------------------------------------------
    //course Enrollment reporting view------------------------------------------------------------------------------------------------------
    private void viweReportCourseEnrollment() {
        Home home;
        try {
            home = new HomeInfo().getHome();
            JRTableModelDataSource dataSource = new JRTableModelDataSource(enrollmentCourseReportTable.getModel());
            HashMap<String, Object> params = new HashMap<>();
            params.put("landLine", home.getLandLine());
            params.put("email", home.getEmail());
            params.put("mobile", home.getMobile());
            params.put("address", home.getLine01() + " " + home.getLine02() + " " + home.getCity());
            params.put("title", "Student Course Enrollment Report");

            new Reporting().viewReport("Student_Course_Enrollment_Report", params, dataSource, admin);

        } catch (IOException ex) {
            LogCenter.logger.log(Level.WARNING, "Error", ex);
        } catch (ClassNotFoundException ex) {
            LogCenter.logger.log(Level.WARNING, "Error", ex);
        } catch (JRException ex) {
            Logger.getLogger(PaymentManagement.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    //course Enrollment reporting view------------------------------------------------------------------------------------------------------
}
