/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package GUI.popup;

import GUI.panal.EnrollmentManagement;
import java.sql.ResultSet;
import java.util.HashMap;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import modal.DB;

/**
 *
 * @author dell
 */
public class EnrollmentClassSelection extends javax.swing.JDialog {

    EnrollmentManagement em;

    /**
     * Creates new form EnrollmentClassSelection
     */
    public EnrollmentClassSelection(EnrollmentManagement parent, boolean modal) {
        em = (EnrollmentManagement) parent;
        initComponents();
        loadSubject();
        loadClasses("SELECT * FROM `class`"
                + "INNER JOIN `teacher` ON `teacher`.`nic` = `class`.`teacher_nic`"
                + "INNER JOIN `class_type` ON `class_type`.`id` = `class`.`class_type_id`"
                + "INNER JOIN `subject` ON `subject`.`id` = `class`.`subject_id`"
                + "INNER JOIN `grade` ON `grade`.`id` = `class`.`grade_id` ORDER BY `class`.`id` ASC");

        DefaultTableCellRenderer renderer = new DefaultTableCellRenderer();
        renderer.setHorizontalAlignment(SwingConstants.CENTER);
        enrollmentClassTable.setDefaultRenderer(Object.class, renderer);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        searchClassIdField = new javax.swing.JTextField();
        searchSubjectCombobox = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        enrollmentClassTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Search By Subject");

        jLabel2.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Search By ID");

        searchClassIdField.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        searchClassIdField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        searchClassIdField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchClassIdFieldKeyReleased(evt);
            }
        });

        searchSubjectCombobox.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        searchSubjectCombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));
        searchSubjectCombobox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                searchSubjectComboboxItemStateChanged(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 204, 204));
        jButton1.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        jButton1.setText("Reset");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchClassIdField, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchSubjectCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(18, 18, 18))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchClassIdField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchSubjectCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        enrollmentClassTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Class ID", "Teacher Name", "Class Type", "Subject", "Grade"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        enrollmentClassTable.getTableHeader().setReorderingAllowed(false);
        enrollmentClassTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                enrollmentClassTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(enrollmentClassTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void enrollmentClassTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enrollmentClassTableMouseClicked
        try {
            int selectedRow = enrollmentClassTable.getSelectedRow();

            // Check if the row is selected and if it's a double-click event
            if (selectedRow != -1 && evt.getClickCount() == 2) {
                if (enrollmentClassSelection != null) {
//             Set the selected student ID to the text field
                    em.getjTextField6().setText(String.valueOf(enrollmentClassTable.getValueAt(selectedRow, 0)));
                    em.getjTextField7().setText(String.valueOf(enrollmentClassTable.getValueAt(selectedRow, 1)));
                    em.getjTextField8().setText(String.valueOf(enrollmentClassTable.getValueAt(selectedRow, 2)));
                    em.getjTextField9().setText(String.valueOf(enrollmentClassTable.getValueAt(selectedRow, 3)));
                    em.getjTextField10().setText(String.valueOf(enrollmentClassTable.getValueAt(selectedRow, 4)));
                }
                this.dispose();
            }
        } catch (Exception e) {
            // Log the exception for debugging (avoid leaving it empty)
            e.printStackTrace();

        }
    }//GEN-LAST:event_enrollmentClassTableMouseClicked

    private void searchClassIdFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchClassIdFieldKeyReleased
        search();
    }//GEN-LAST:event_searchClassIdFieldKeyReleased

    private void searchSubjectComboboxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_searchSubjectComboboxItemStateChanged
        search1();
    }//GEN-LAST:event_searchSubjectComboboxItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        searchClassIdField.setText("");
        searchSubjectCombobox.setSelectedIndex(0);
        loadClasses("SELECT * FROM `class`"
                + "INNER JOIN `teacher` ON `teacher`.`nic` = `class`.`teacher_nic`"
                + "INNER JOIN `class_type` ON `class_type`.`id` = `class`.`class_type_id`"
                + "INNER JOIN `subject` ON `subject`.`id` = `class`.`subject_id`"
                + "INNER JOIN `grade` ON `grade`.`id` = `class`.`grade_id` ORDER BY `class`.`id` ASC");
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable enrollmentClassTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField searchClassIdField;
    private javax.swing.JComboBox<String> searchSubjectCombobox;
    // End of variables declaration//GEN-END:variables

    private EnrollmentClassSelection enrollmentClassSelection;

    public void setEnrollment(EnrollmentClassSelection enrollmentClassSelection) {
        this.enrollmentClassSelection = enrollmentClassSelection;
    }
    
        public static HashMap<String, String> teacherMap = new HashMap<>(); //for get id from teacher
        public static HashMap<String, String> classTypeMap = new HashMap<>(); //for get id from class type
        public static HashMap<String, String> subjectMap = new HashMap<>(); //for get id from subject
        public static HashMap<String, String> gradeMap = new HashMap<>(); //for get id from grade


    private void loadSubject() {
        try {

            ResultSet resultSet = DB.search("SELECT `name` FROM `subject`");

            Vector vector = new Vector();

            vector.add("Select");

            while (resultSet.next()) {
                vector.add(resultSet.getString("name"));
            }

            DefaultComboBoxModel ComboBoxModel = new DefaultComboBoxModel(vector);
            searchSubjectCombobox.setModel(ComboBoxModel);

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void loadClasses(String query) {

        try {

            ResultSet resultSet = DB.search(query);

            DefaultTableModel tableModel = (DefaultTableModel) enrollmentClassTable.getModel();
            tableModel.setRowCount(0);

            while (resultSet.next()) {
                Vector vector = new Vector();
                vector.add(resultSet.getString("id"));
                vector.add(resultSet.getString("teacher.fname") + " " + resultSet.getString("teacher.lname"));
                vector.add(resultSet.getString("class_type.type"));
                vector.add(resultSet.getString("subject.name"));
                vector.add(resultSet.getString("grade.name"));
                
               teacherMap.put(resultSet.getString("fname"), resultSet.getString("id"));
               classTypeMap.put(resultSet.getString("type"), resultSet.getString("id"));
               subjectMap.put(resultSet.getString("name"), resultSet.getString("id"));
               gradeMap.put(resultSet.getString("name"), resultSet.getString("id"));

                tableModel.addRow(vector);
            }

        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    private void search() {
        String id = searchClassIdField.getText();
        loadClasses("SELECT * FROM `class`"
                + "INNER JOIN `teacher` ON `teacher`.`nic` = `class`.`teacher_nic`"
                + "INNER JOIN `class_type` ON `class_type`.`id` = `class`.`class_type_id`"
                + "INNER JOIN `subject` ON `subject`.`id` = `class`.`subject_id`"
                + "INNER JOIN `grade` ON `grade`.`id` = `class`.`grade_id` WHERE `class`.`id` LIKE '%" + id + "%' ORDER BY `class`.`id` ASC");
    }

    private void search1() {

        String subject = String.valueOf(searchSubjectCombobox.getSelectedItem());
        loadClasses("SELECT * FROM `class`"
                + "INNER JOIN `teacher` ON `teacher`.`nic` = `class`.`teacher_nic`"
                + "INNER JOIN `class_type` ON `class_type`.`id` = `class`.`class_type_id`"
                + "INNER JOIN `subject` ON `subject`.`id` = `class`.`subject_id`"
                + "INNER JOIN `grade` ON `grade`.`id` = `class`.`grade_id` WHERE `subject`.`name` LIKE '%" + subject + "%' ORDER BY `class`.`id` ASC");
    }

}
