package GUI.popup;

import java.awt.HeadlessException;
import java.io.IOException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import modal.DB;
import modal.LogCenter;
import modal.RoundedPanel;
import java.awt.Color;
import raven.toast.Notifications;

/**
 *
 * @author dell
 */
public class UpdateEnrollments extends javax.swing.JDialog {

    /**
     * Creates new form UpdateEnrollments
     */
    public UpdateEnrollments(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        loadPaymentModel();
        loadStatus();
        loadClassesEnrollment("SELECT * FROM `class_enrollment`"
                + "INNER JOIN `class` ON `class`.`id` = `class_enrollment`.`class_id`"
                + "INNER JOIN `student` ON `student`.`id` = `class_enrollment`.`student_id`"
                + "INNER JOIN `enrollment_status` ON `enrollment_status`.`id` = `class_enrollment`.`enrollment_status_id`"
                + "INNER JOIN `employee` ON `employee`.`id` = `class_enrollment`.`employee_id`"
                + "INNER JOIN `payment_modal` ON `payment_modal`.`id` = `class_enrollment`.`payment_modal_id` ORDER BY `class_enrollment`.`id` ASC");
        loadCoursesEnrollment("SELECT * FROM `course_enrollment`"
                + "INNER JOIN `course` ON `course`.`id` = `course_enrollment`.`course_id`"
                + "INNER JOIN `student` ON `student`.`id` = `course_enrollment`.`student_id`"
                + "INNER JOIN `enrollment_status` ON `enrollment_status`.`id` = `course_enrollment`.`enrollment_status_id`"
                + "INNER JOIN `employee` ON `employee`.`id` = `course_enrollment`.`employee_id`"
                + "INNER JOIN `payment_modal` ON `payment_modal`.`id` = `course_enrollment`.`payment_modal_id` ORDER BY `course_enrollment`.`id` ASC");

        DefaultTableCellRenderer renderer = new DefaultTableCellRenderer();
        renderer.setHorizontalAlignment(SwingConstants.CENTER);
        updateTable1.setDefaultRenderer(Object.class, renderer);
        updateTable2.setDefaultRenderer(Object.class, renderer);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new RoundedPanel(20, new Color(250,249,246));
        jPanel12 = new RoundedPanel(20, new Color(234,238,244));
        jLabel15 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        searchStudentIDField1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        searchcClassIDField = new javax.swing.JTextField();
        classFindButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        updateTable1 = new javaswingdev.swing.table.Table();
        jPanel2 = new RoundedPanel(20, new Color(250,249,246));
        paymentModalCombobox = new javax.swing.JComboBox<>();
        classCourseIdTextField = new javax.swing.JTextField();
        studentTextField = new javax.swing.JTextField();
        statusCombobox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        saveChangesButton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel5 = new RoundedPanel(20, new Color(250,249,246));
        jPanel13 = new RoundedPanel(20, new Color(234,238,244));
        jLabel16 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        searchStudendIDField2 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        searchCourseIDField = new javax.swing.JTextField();
        courseUpdateFindButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        updateTable2 = new javaswingdev.swing.table.Table();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);

        jPanel3.setBackground(new java.awt.Color(200, 200, 198));

        jPanel4.setBackground(new java.awt.Color(200, 200, 198));

        jPanel12.setBackground(new java.awt.Color(250, 249, 246));

        jLabel15.setBackground(new java.awt.Color(250, 249, 246));
        jLabel15.setFont(new java.awt.Font("Poppins SemiBold", 1, 20)); // NOI18N
        jLabel15.setText("Class Enrollment");
        jLabel15.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel15)
        );

        jLabel5.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Search By Student ID");

        searchStudentIDField1.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        searchStudentIDField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel6.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Search By Class ID");

        searchcClassIDField.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        searchcClassIDField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        classFindButton.setBackground(new java.awt.Color(102, 255, 153));
        classFindButton.setFont(new java.awt.Font("Poppins SemiBold", 1, 14)); // NOI18N
        classFindButton.setText("Find");
        classFindButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        classFindButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                classFindButtonActionPerformed(evt);
            }
        });

        updateTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Class Enrollment ID", "Class ID", "Student ID", "Enrollment Status", "Register Date", "Employee", "Payment Model"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        updateTable1.getTableHeader().setReorderingAllowed(false);
        updateTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(updateTable1);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(searchStudentIDField1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(93, 93, 93)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(searchcClassIDField, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(classFindButton, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchStudentIDField1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchcClassIDField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(classFindButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(200, 200, 198));

        paymentModalCombobox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        paymentModalCombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));

        classCourseIdTextField.setEditable(false);
        classCourseIdTextField.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        classCourseIdTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        studentTextField.setEditable(false);
        studentTextField.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        studentTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        statusCombobox.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        statusCombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));

        jLabel1.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Student");

        jLabel3.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Class / Course ");

        jLabel2.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Payment Modal");

        jLabel4.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Status");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(studentTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(classCourseIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(paymentModalCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(statusCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(studentTextField)
                    .addComponent(classCourseIdTextField)
                    .addComponent(statusCombobox)
                    .addComponent(paymentModalCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
        );

        saveChangesButton.setBackground(new java.awt.Color(51, 255, 51));
        saveChangesButton.setFont(new java.awt.Font("Poppins SemiBold", 1, 14)); // NOI18N
        saveChangesButton.setText("Save Changes");
        saveChangesButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        saveChangesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveChangesButtonActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 51, 51));
        jButton2.setFont(new java.awt.Font("Poppins SemiBold", 1, 14)); // NOI18N
        jButton2.setText("Clear");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(200, 200, 198));

        jPanel13.setBackground(new java.awt.Color(250, 249, 246));

        jLabel16.setBackground(new java.awt.Color(250, 249, 246));
        jLabel16.setFont(new java.awt.Font("Poppins SemiBold", 1, 20)); // NOI18N
        jLabel16.setText("Class Enrollment");
        jLabel16.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel16)
        );

        jLabel7.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Search By Student ID");

        searchStudendIDField2.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        searchStudendIDField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel8.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Search By Course ID");

        searchCourseIDField.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        searchCourseIDField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        courseUpdateFindButton.setBackground(new java.awt.Color(102, 255, 153));
        courseUpdateFindButton.setFont(new java.awt.Font("Poppins SemiBold", 1, 14)); // NOI18N
        courseUpdateFindButton.setText("Find");
        courseUpdateFindButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        courseUpdateFindButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                courseUpdateFindButtonActionPerformed(evt);
            }
        });

        updateTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Course Enrollment ID", "Course ID", "Student ID", "Enrollment Status", "Register Date", "Employee", "Payment Model"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        updateTable2.getTableHeader().setReorderingAllowed(false);
        updateTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(updateTable2);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(searchStudendIDField2, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(88, 88, 88)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(searchCourseIDField, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(courseUpdateFindButton, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchStudendIDField2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchCourseIDField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(courseUpdateFindButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(saveChangesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveChangesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        reset();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void saveChangesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveChangesButtonActionPerformed

        updateEnrollment();
    }//GEN-LAST:event_saveChangesButtonActionPerformed

    private void classFindButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_classFindButtonActionPerformed
        searchClassUpdateEnroll();
    }//GEN-LAST:event_classFindButtonActionPerformed

    private void courseUpdateFindButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_courseUpdateFindButtonActionPerformed
        searchUpdateCourseEnroll();
    }//GEN-LAST:event_courseUpdateFindButtonActionPerformed

    private void updateTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateTable1MouseClicked
        try {

            int selectedRow = updateTable1.getSelectedRow();

            if (evt.getClickCount() == 2) {

                if (selectedRow != -1) {

                    studentTextField.setText(String.valueOf(updateTable1.getValueAt(selectedRow, 2)));
                    classCourseIdTextField.setText(String.valueOf(updateTable1.getValueAt(selectedRow, 1)));
                    paymentModalCombobox.setSelectedItem(updateTable1.getValueAt(selectedRow, 6));
                    statusCombobox.setSelectedItem(updateTable1.getValueAt(selectedRow, 3));

                }

            }
        } catch (Exception e) {
            LogCenter.logger.log(java.util.logging.Level.WARNING, "updateTable1MouseClicked", e);
        }
    }//GEN-LAST:event_updateTable1MouseClicked

    private void updateTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateTable2MouseClicked
        try {

            int selectedRow = updateTable2.getSelectedRow();

            if (evt.getClickCount() == 2) {

                if (selectedRow != -1) {

                    studentTextField.setText(String.valueOf(updateTable2.getValueAt(selectedRow, 2)));
                    classCourseIdTextField.setText(String.valueOf(updateTable2.getValueAt(selectedRow, 1)));
                    paymentModalCombobox.setSelectedItem(updateTable2.getValueAt(selectedRow, 6));
                    statusCombobox.setSelectedItem(updateTable2.getValueAt(selectedRow, 3));

                }

            }
        } catch (Exception e) {
            LogCenter.logger.log(java.util.logging.Level.WARNING, "updateTable2MouseClicked", e);
        }
    }//GEN-LAST:event_updateTable2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateEnrollments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateEnrollments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateEnrollments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateEnrollments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                UpdateEnrollments dialog = new UpdateEnrollments(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField classCourseIdTextField;
    private javax.swing.JButton classFindButton;
    private javax.swing.JButton courseUpdateFindButton;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox<String> paymentModalCombobox;
    private javax.swing.JButton saveChangesButton;
    private javax.swing.JTextField searchCourseIDField;
    private javax.swing.JTextField searchStudendIDField2;
    private javax.swing.JTextField searchStudentIDField1;
    private javax.swing.JTextField searchcClassIDField;
    private javax.swing.JComboBox<String> statusCombobox;
    private javax.swing.JTextField studentTextField;
    private javaswingdev.swing.table.Table updateTable1;
    private javaswingdev.swing.table.Table updateTable2;
    // End of variables declaration//GEN-END:variables

    private static HashMap<String, String> paymentModelMap = new HashMap<>(); //for get id from payment model
    private static HashMap<String, String> enrollmentStatusMap = new HashMap<>(); //for get id from status

    private void loadClassesEnrollment(String query) {
        try {

            ResultSet resultSet = DB.search(query);

            DefaultTableModel tableModel = (DefaultTableModel) updateTable1.getModel();
            tableModel.setRowCount(0);

            while (resultSet.next()) {
                Vector vector = new Vector();
                vector.add(resultSet.getString("id"));
                vector.add(resultSet.getString("class.id"));
                vector.add(resultSet.getString("student.id"));
                vector.add(resultSet.getString("enrollment_status.name"));
                vector.add(resultSet.getString("register_date"));
                vector.add(resultSet.getString("employee.fname") + " " + resultSet.getString("employee.lname"));
                vector.add(resultSet.getString("payment_modal.modal"));

                tableModel.addRow(vector);
            }

        } catch (ClassNotFoundException | SQLException e) {
            e.printStackTrace();
        } catch (IOException ex) {
            LogCenter.logger.log(java.util.logging.Level.WARNING, "Database Connecting Problem", ex);
        }

    }

    private void loadCoursesEnrollment(String query) {
        try {

            ResultSet resultSet = DB.search(query);

            DefaultTableModel tableModel = (DefaultTableModel) updateTable2.getModel();
            tableModel.setRowCount(0);

            while (resultSet.next()) {
                Vector vector = new Vector();
                vector.add(resultSet.getString("id"));
                vector.add(resultSet.getString("course.id"));
                vector.add(resultSet.getString("student.id"));
                vector.add(resultSet.getString("enrollment_status.name"));
                vector.add(resultSet.getString("register_date"));
                vector.add(resultSet.getString("employee.fname") + " " + resultSet.getString("employee.lname"));
                vector.add(resultSet.getString("payment_modal.modal"));

                tableModel.addRow(vector);
            }

        } catch (ClassNotFoundException | SQLException e) {
            e.printStackTrace();
        } catch (IOException ex) {
            LogCenter.logger.log(java.util.logging.Level.WARNING, "Database Connecting Problem", ex);
        }
    }

    private void loadPaymentModel() {
        try {

            ResultSet resultSet = DB.search("SELECT * FROM `payment_modal`");

            Vector<String> vector = new Vector<>();

            vector.add("Select");

            while (resultSet.next()) {
                vector.add(resultSet.getString("modal"));
                paymentModelMap.put(resultSet.getString("modal"), resultSet.getString("id"));

            }

            DefaultComboBoxModel<String> comboBoxModel = new DefaultComboBoxModel<>(vector);
            paymentModalCombobox.setModel(comboBoxModel);

        } catch (ClassNotFoundException | SQLException e) {
            e.printStackTrace();
        } catch (IOException ex) {
            LogCenter.logger.log(java.util.logging.Level.WARNING, "Database Connecting Problem", ex);
        }
    }

    private void loadStatus() {
        try {

            ResultSet resultSet = DB.search("SELECT * FROM `enrollment_status`");

            Vector<String> vector = new Vector<>();

            vector.add("Select");

            while (resultSet.next()) {
                vector.add(resultSet.getString("name"));
                enrollmentStatusMap.put(resultSet.getString("name"), resultSet.getString("id"));

            }

            DefaultComboBoxModel<String> comboBoxModel = new DefaultComboBoxModel<>(vector);
            statusCombobox.setModel(comboBoxModel);

        } catch (ClassNotFoundException | SQLException e) {
            e.printStackTrace();
        } catch (IOException ex) {
            LogCenter.logger.log(java.util.logging.Level.WARNING, "Database Connecting Problem", ex);
        }
    }

    //class Update Enrollment Search part-------------------------------------------------------------------------------
    // Method to search class enrollment by Student ID or Class ID
    private void searchClassUpdateEnroll() {
        // Retrieve user input from the search fields
        String studentID = searchStudentIDField1.getText().trim(); // Search by Student ID
        String classID = searchcClassIDField.getText().trim();      // Search by Class ID

        try {
            // Ensure that at least one of the fields is provided
            if (!studentID.isEmpty() || !classID.isEmpty()) {
                // Build the SQL query dynamically based on the provided input
                StringBuilder query = new StringBuilder(
                        "SELECT * FROM `class_enrollment`"
                        + " INNER JOIN `class` ON `class`.`id` = `class_enrollment`.`class_id`"
                        + " INNER JOIN `student` ON `student`.`id` = `class_enrollment`.`student_id`"
                        + " INNER JOIN `enrollment_status` ON `enrollment_status`.`id` = `class_enrollment`.`enrollment_status_id`"
                        + " INNER JOIN `employee` ON `employee`.`id` = `class_enrollment`.`employee_id`"
                        + " INNER JOIN `payment_modal` ON `payment_modal`.`id` = `class_enrollment`.`payment_modal_id`"
                        + " WHERE 1=1 "); // Default condition to allow appending filters

                // Add filters based on input
                if (!studentID.isEmpty()) {
                    query.append(" AND `student`.`id` LIKE '%").append(studentID).append("%'");
                }
                if (!classID.isEmpty()) {
                    query.append(" AND `class`.`id` LIKE '%").append(classID).append("%'");
                }

                query.append(" ORDER BY `class_enrollment`.`id` ASC");

                // Pass the query to the method that loads the enrollment data
                loadClassesEnrollment(query.toString());
            } else {
                // Show an error message if both fields are empty
                Notifications.getInstance().show(Notifications.Type.WARNING, Notifications.Location.TOP_CENTER,
                    "Please enter a Student ID or Class ID to search");
            }
        } catch (Exception e) {
           LogCenter.logger.log(java.util.logging.Level.WARNING, "searchClassUpdateEnroll", e);
        }
    }

    //class Update Enrollment Search part-------------------------------------------------------------------------------
    //course Update Enrollment Search part-------------------------------------------------------------------------------
    private void searchUpdateCourseEnroll() {
        // Retrieve user input from the search fields
        String studentID = searchStudendIDField2.getText().trim(); // Search by Student ID
        String courseID = searchCourseIDField.getText().trim();   // Search by Course ID

        try {
            // Ensure at least one input is provided
            if (!studentID.isEmpty() || !courseID.isEmpty()) {
                // Build the base query
                StringBuilder query = new StringBuilder(
                        "SELECT * FROM `course_enrollment`"
                        + " INNER JOIN `course` ON `course`.`id` = `course_enrollment`.`course_id`"
                        + " INNER JOIN `student` ON `student`.`id` = `course_enrollment`.`student_id`"
                        + " INNER JOIN `enrollment_status` ON `enrollment_status`.`id` = `course_enrollment`.`enrollment_status_id`"
                        + " INNER JOIN `employee` ON `employee`.`id` = `course_enrollment`.`employee_id`"
                        + " INNER JOIN `payment_modal` ON `payment_modal`.`id` = `course_enrollment`.`payment_modal_id`"
                        + " WHERE 1=1 "); // Base condition to append filters dynamically

                // Add conditions based on user input
                if (!studentID.isEmpty()) {
                    query.append(" AND `student`.`id` LIKE '%").append(studentID).append("%'");
                }
                if (!courseID.isEmpty()) {
                    query.append(" AND `course`.`id` LIKE '%").append(courseID).append("%'");
                }

                // Append ordering clause
                query.append(" ORDER BY `course_enrollment`.`id` ASC");

                // Execute the query
                loadCoursesEnrollment(query.toString());
            } else {
                // Show an error message if both fields are empty
                Notifications.getInstance().show(Notifications.Type.WARNING, Notifications.Location.TOP_CENTER,
                    "Please enter a Student ID or Course ID to search");
            }
        } catch (Exception e) {
            LogCenter.logger.log(java.util.logging.Level.WARNING, "searchUpdateCourseEnroll", e);
        }
    }

    //course Update Enrollment Search part-------------------------------------------------------------------------------
    private void updateEnrollment() {
        try {
            String student = studentTextField.getText();
            String ClassCourse = classCourseIdTextField.getText();
            String pmoodel = String.valueOf(paymentModalCombobox.getSelectedItem());
            String status = String.valueOf(statusCombobox.getSelectedItem());

            if (student.isEmpty()) {
                Notifications.getInstance().show(Notifications.Type.WARNING, Notifications.Location.TOP_CENTER,
                    "Select A row From Tables");
            } else if (ClassCourse.isEmpty()) {
                Notifications.getInstance().show(Notifications.Type.WARNING, Notifications.Location.TOP_CENTER,
                    "Select A row From Tables");
            } else if (pmoodel.equals("Select")) {
                Notifications.getInstance().show(Notifications.Type.WARNING, Notifications.Location.TOP_CENTER,
                    "Select Payment Modal");
            } else if (status.equals("Select")) {
                Notifications.getInstance().show(Notifications.Type.WARNING, Notifications.Location.TOP_CENTER,
                    "Select Enrolment Status");
            } else {
                // update class enrollment
                if (ClassCourse.matches("CL\\d{6}")) {

                    ResultSet resultSet = DB.search("SELECT * FROM `class_enrollment` WHERE `class_id` = '" + ClassCourse + "' AND `student_id` = '" + student + "' AND `enrollment_status_id` = '" + enrollmentStatusMap.get(status) + "' AND `payment_modal_id` = '" + paymentModelMap.get(pmoodel) + "'");

                    if (resultSet.next()) {
                        Notifications.getInstance().show(Notifications.Type.WARNING, Notifications.Location.TOP_CENTER,
                    "No Updates Available");
                    } else {
                        DB.IUD("UPDATE `class_enrollment`"
                                + "SET `payment_modal_id` = '" + paymentModelMap.get(pmoodel) + "', `enrollment_status_id` = '" + enrollmentStatusMap.get(status) + "'"
                                + "WHERE `student_id` = '" + student + "' AND `class_id` = '" + ClassCourse + "'");
                        Notifications.getInstance().show(Notifications.Type.SUCCESS, Notifications.Location.TOP_CENTER,
                    "Class Enrollment Update Successfull");
                        reset();
                    }

                    //update course enrollment
                } else if (ClassCourse.matches("CO\\d{6}")) {
                    ResultSet resultSet = DB.search("SELECT * FROM `course_enrollment` WHERE `course_id` = '" + ClassCourse + "' AND `student_id` = '" + student + "' AND `enrollment_status_id` = '" + enrollmentStatusMap.get(status) + "' AND `payment_modal_id` = '" + paymentModelMap.get(pmoodel) + "'");

                    if (resultSet.next()) {
                        Notifications.getInstance().show(Notifications.Type.WARNING, Notifications.Location.TOP_CENTER,
                    "No Updates Available");
                    } else {
                        DB.IUD("UPDATE `course_enrollment`"
                                + "SET `payment_modal_id` = '" + paymentModelMap.get(pmoodel) + "', `enrollment_status_id` = '" + enrollmentStatusMap.get(status) + "'"
                                + "WHERE `student_id` = '" + student + "' AND `course_id` = '" + ClassCourse + "'");

                        Notifications.getInstance().show(Notifications.Type.SUCCESS, Notifications.Location.TOP_CENTER,
                    "Course Enrollment Update Successfull");
                        reset();
                    }
                }

                this.dispose();

            }
        } catch (HeadlessException | ClassNotFoundException | SQLException e) {
            e.printStackTrace();
        } catch (IOException ex) {
            LogCenter.logger.log(java.util.logging.Level.WARNING, "Database Connecting Problem", ex);
        }
    }

    private void reset() {
        searchCourseIDField.setText("");
        searchStudendIDField2.setText("");
        searchStudentIDField1.setText("");
        searchcClassIDField.setText("");
        studentTextField.setText("");
        classCourseIdTextField.setText("");
        paymentModalCombobox.setSelectedIndex(0);
        statusCombobox.setSelectedIndex(0);
        loadClassesEnrollment("SELECT * FROM `class_enrollment`"
                + "INNER JOIN `class` ON `class`.`id` = `class_enrollment`.`class_id`"
                + "INNER JOIN `student` ON `student`.`id` = `class_enrollment`.`student_id`"
                + "INNER JOIN `enrollment_status` ON `enrollment_status`.`id` = `class_enrollment`.`enrollment_status_id`"
                + "INNER JOIN `employee` ON `employee`.`id` = `class_enrollment`.`employee_id`"
                + "INNER JOIN `payment_modal` ON `payment_modal`.`id` = `class_enrollment`.`payment_modal_id` ORDER BY `class_enrollment`.`id` ASC");
        loadCoursesEnrollment("SELECT * FROM `course_enrollment`"
                + "INNER JOIN `course` ON `course`.`id` = `course_enrollment`.`course_id`"
                + "INNER JOIN `student` ON `student`.`id` = `course_enrollment`.`student_id`"
                + "INNER JOIN `enrollment_status` ON `enrollment_status`.`id` = `course_enrollment`.`enrollment_status_id`"
                + "INNER JOIN `employee` ON `employee`.`id` = `course_enrollment`.`employee_id`"
                + "INNER JOIN `payment_modal` ON `payment_modal`.`id` = `course_enrollment`.`payment_modal_id` ORDER BY `course_enrollment`.`id` ASC");
    }

}
